source("methylation_functions.R")
rgSet<-load_data(sampleSheetPattern = "SampleSheet",working_dir = "\\\\CGS-FS3\\CGS-FS3\\SERVICES\\Methylation\\")
gmSet<-preprocess_data(rgSet)
plotCOntrols(rgSet,"control_plots")
basedir=getwd()
dir.create("QC")
setwd("QC")
qc<-QCinfo(rgSet)
setwd(basedir)

plotgmSetQC(gmSet, "gmsetQC")
plotMDS(gmSet = gmSet, dirForGraph = "MDS", "Slide")
plotMDS(gmSet = gmSet, dirForGraph = "MDS", "Sample_Group")
plotMDS(gmSet, dirForGraph = "MDS", "Gender")

bump<-compare_groups(gmSet)
plotDMRs(gmSet, bump,"DMRS_plot")